### ISSUE TITLE
Where the heck is alpha release???

### ISSUE THREAD

**Issue by dalechyn** [Coestaris/DeepCars#2]
## I want to test the game!!!
WHERE?

**Comment by Coestaris** [comment]
@h0tw4t3r every single commit is pre alpha release 😎

**Comment by Coestaris** [comment]
@h0tw4t3r but you can help the project by completing/rewriting the machine learning library. This will expedite releasing prealpha version for about 2 years

**Comment by dalechyn** [comment]
I will put this on my todo list!
